#!/bin/bash
# Builds ~/Applications/Verstas.app: a launcher for this checkout that you
# can keep in the Dock. Nothing is packaged or published. The bundle is a
# renamed copy of the Electron runtime in node_modules, and its only app
# code is a one-line entry that loads electron/main.mjs from this checkout,
# so a `git pull` and `npm run setup` are picked up on the next launch.
#
# Run it again after an Electron upgrade (npm install), or to move the
# launcher to another checkout:   bash scripts/macos-app.sh [target.app]
set -euo pipefail

repo="$(cd "$(dirname "$0")/.." && pwd)"
target="${1:-$HOME/Applications/Verstas.app}"
electron="$repo/node_modules/electron/dist/Electron.app"

[ -d "$electron" ] || { echo "No Electron in $repo/node_modules; run npm install first." >&2; exit 1; }
[ -f "$repo/dist/src/server.js" ] || echo "Note: the app is not built yet; run npm run setup before the first launch." >&2

mkdir -p "$(dirname "$target")"
rm -rf "$target"
cp -R "$electron" "$target"

# The entry Electron loads from Contents/Resources/app.
app="$target/Contents/Resources/app"
mkdir -p "$app"
cat > "$app/package.json" <<EOF
{ "name": "verstas", "productName": "Verstas", "main": "main.mjs", "type": "module" }
EOF
cat > "$app/main.mjs" <<EOF
// Generated by scripts/macos-app.sh: run Verstas from its checkout.
await import(new URL("file://$repo/electron/main.mjs").href);
EOF

# Name and identity, so the Dock, the menu bar and Cmd-Tab say Verstas.
plist="$target/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleName Verstas" "$plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName Verstas" "$plist" 2>/dev/null || /usr/libexec/PlistBuddy -c "Add :CFBundleDisplayName string Verstas" "$plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier dev.verstas.local" "$plist"

# The hammer (electron/icon.svg; re-render with scripts/render-icon.mjs).
[ -f "$repo/electron/icon.icns" ] && cp "$repo/electron/icon.icns" "$target/Contents/Resources/electron.icns"

# Editing Info.plist breaks Electron's signature; sign it again, ad hoc, for this machine.
codesign --force --deep --sign - "$target" >/dev/null 2>&1
touch "$target"

echo "Built $target"
echo "Open it once from Finder (or: open \"$target\"), then right-click its Dock icon > Options > Keep in Dock."
